In [1]:
import numpy as np
import pandas as pd

import os
from scipy.io import loadmat

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
print(os.listdir('devkit/'))

['train_perfect_preds.txt', 'README.txt', 'cars_test_annos.mat', 'cars_train_annos.mat', 'cars_meta.mat', 'eval_train.m']


In [3]:
!cat devkit/README.txt

This file gives documentation for the cars 196 dataset.
(http://ai.stanford.edu/~jkrause/cars/car_dataset.html)

----------------------------------------
Metadata/Annotations
----------------------------------------
Descriptions of the files are as follows:

-cars_meta.mat:
  Contains a cell array of class names, one for each class.

-cars_train_annos.mat:
  Contains the variable 'annotations', which is a struct array of length
  num_images and where each element has the fields:
    bbox_x1: Min x-value of the bounding box, in pixels
    bbox_x2: Max x-value of the bounding box, in pixels
    bbox_y1: Min y-value of the bounding box, in pixels
    bbox_y2: Max y-value of the bounding box, in pixels
    class: Integral id of the class the image belongs to.
    fname: Filename of the image within the folder of images.

-cars_test_annos.mat:
  Same format as 'cars_train_annos.mat', except the class is not provided.

----------------------------------------
Submission file format
---------

In [36]:
# lets store the information in the dataframe
mat = loadmat('devkit/cars_meta.mat')

classes = []
for C in mat['class_names'][0]:
    classes.append(C[0])
classes = pd.DataFrame(classes,columns=['class_name'])

#blankidx = [''] * len(classes)
#classes.index = blankidx
classes.head()

In [38]:
# lets store the data in the dataFrame
mat = loadmat('devkit/cars_train_annos.mat')
mat

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 'annotations': array([[ (array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'],
       dtype='<U9')),
         (array([[36]], dtype=uint8), array([[116]], dtype=uint8), array([[868]], dtype=uint16), array([[587]], dtype=uint16), array([[3]], dtype=uint8), array(['00002.jpg'],
       dtype='<U9')),
         (array([[85]], dtype=uint8), array([[109]], dtype=uint8), array([[601]], dtype=uint16), array([[381]], dtype=uint16), array([[91]], dtype=uint8), array(['00003.jpg'],
       dtype='<U9')),
         ...,
         (array([[26]], dtype=uint8), array([[246]], dtype=uint8), array([[660]], dtype=uint16), array([[449]], dtype=uint16), array([[163]], dtype=uint8), array(['08142.jpg'],
       dtype='<U9')),
         (array([[78]], dtype=uint8), a

In [54]:
train_df = []
for row in mat['annotations'][0]:
    train_df.append([row[0][0][0],    # min x
                     row[1][0][0],    # max x
                     row[2][0][0],    # min y
                     row[3][0][0],    # max y
                     row[4][0][0],    # class
                     row[5][0]])   # file name


train_df = pd.DataFrame(train_df, columns=['min_x', 'min_y', 'max_x', 'max_y',
                                           'class_name', 'file_name'])
train_df.head()

min_x  min_y  max_x  max_y  class_name  file_name
0     39    116    569    375          14  00001.jpg
1     36    116    868    587           3  00002.jpg
2     85    109    601    381          91  00003.jpg
3    621    393   1484   1096         134  00004.jpg
4     14     36    133     99         106  00005.jpg